//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlumbingProps.Document {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExcelParts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExcelParts() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PlumbingProps.Document.ExcelParts", typeof(ExcelParts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 500.
        /// </summary>
        internal static string limitColumn {
            get {
                return ResourceManager.GetString("limitColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 10000.
        /// </summary>
        internal static string limitRows {
            get {
                return ResourceManager.GetString("limitRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cell.
        /// </summary>
        internal static string tagCell {
            get {
                return ResourceManager.GetString("tagCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Data.
        /// </summary>
        internal static string tagData {
            get {
                return ResourceManager.GetString("tagData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DateTime.
        /// </summary>
        internal static string tagDataDatetime {
            get {
                return ResourceManager.GetString("tagDataDatetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Number.
        /// </summary>
        internal static string tagDataNumber {
            get {
                return ResourceManager.GetString("tagDataNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a String.
        /// </summary>
        internal static string tagDataString {
            get {
                return ResourceManager.GetString("tagDataString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ExpandedColumnCount.
        /// </summary>
        internal static string tagExpandedColumnCount {
            get {
                return ResourceManager.GetString("tagExpandedColumnCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ExpandedRowCount.
        /// </summary>
        internal static string tagExpandedRowCount {
            get {
                return ResourceManager.GetString("tagExpandedRowCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formula.
        /// </summary>
        internal static string tagFormula {
            get {
                return ResourceManager.GetString("tagFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Index.
        /// </summary>
        internal static string tagIndex {
            get {
                return ResourceManager.GetString("tagIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Row.
        /// </summary>
        internal static string tagRow {
            get {
                return ResourceManager.GetString("tagRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Table.
        /// </summary>
        internal static string tagTable {
            get {
                return ResourceManager.GetString("tagTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type.
        /// </summary>
        internal static string tagType {
            get {
                return ResourceManager.GetString("tagType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ss.
        /// </summary>
        internal static string tagTypeNamespace {
            get {
                return ResourceManager.GetString("tagTypeNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Worksheet.
        /// </summary>
        internal static string tagWorkSheet {
            get {
                return ResourceManager.GetString("tagWorkSheet", resourceCulture);
            }
        }
    }
}
