//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlumbingProps.Document {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WordParts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WordParts() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PlumbingProps.Document.WordParts", typeof(WordParts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a val.
        /// </summary>
        internal static string prefijo {
            get {
                return ResourceManager.GetString("prefijo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;w:br/&gt;.
        /// </summary>
        internal static string tagEnter {
            get {
                return ResourceManager.GetString("tagEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;w:tblGrid&gt;.
        /// </summary>
        internal static string tagGrid {
            get {
                return ResourceManager.GetString("tagGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;w:tc&gt;
        ///      &lt;w:tcPr&gt;
        ///        &lt;w:tcW w:w=&quot;3259&quot; w:type=&quot;dxa&quot; /&gt;
        ///        &lt;w:shd w:val=&quot;clear&quot; w:color=&quot;auto&quot; w:fill=&quot;EEECE1&quot; /&gt;
        ///      &lt;/w:tcPr&gt;
        ///      &lt;w:p wsp:rsidR=&quot;002A7E54&quot; wsp:rsidRPr=&quot;006C7DFD&quot;
        ///      wsp:rsidRDefault=&quot;002A7E54&quot; wsp:rsidP=&quot;006C7DFD&quot;&gt;
        ///        &lt;w:pPr&gt;
        ///          &lt;w:spacing w:after=&quot;0&quot; w:line=&quot;240&quot; w:line-rule=&quot;auto&quot; /&gt;
        ///          &lt;w:rPr&gt;
        ///            &lt;w:lang w:val=&quot;ES&quot; /&gt;
        ///          &lt;/w:rPr&gt;
        ///        &lt;/w:pPr&gt;
        ///        &lt;w:r wsp:rsidRPr=&quot;006C7DFD&quot;&gt;
        ///          &lt;w:rPr&gt;
        ///            &lt;w:lang w:val=&quot;ES&quot;  [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string tagGridCellTitle {
            get {
                return ResourceManager.GetString("tagGridCellTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;w:tc&gt;
        ///      &lt;w:tcPr&gt;
        ///        &lt;w:tcW w:w=&quot;3259&quot; w:type=&quot;dxa&quot; /&gt;
        ///        &lt;w:shd w:val=&quot;clear&quot; w:color=&quot;auto&quot; w:fill=&quot;auto&quot; /&gt;
        ///      &lt;/w:tcPr&gt;
        ///      &lt;w:p wsp:rsidR=&quot;002A7E54&quot; wsp:rsidRPr=&quot;006C7DFD&quot;
        ///      wsp:rsidRDefault=&quot;00446018&quot; wsp:rsidP=&quot;006C7DFD&quot;&gt;
        ///        &lt;w:pPr&gt;
        ///          &lt;w:spacing w:after=&quot;0&quot; w:line=&quot;240&quot; w:line-rule=&quot;auto&quot; /&gt;
        ///          &lt;w:rPr&gt;
        ///            &lt;w:lang w:val=&quot;ES&quot; /&gt;
        ///          &lt;/w:rPr&gt;
        ///        &lt;/w:pPr&gt;
        ///        &lt;w:r wsp:rsidRPr=&quot;006C7DFD&quot;&gt;
        ///          &lt;w:rPr&gt;
        ///            &lt;w:lan [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string tagGridCellValue {
            get {
                return ResourceManager.GetString("tagGridCellValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;w:gridCol w:w=&quot;{0}&quot; /&gt;.
        /// </summary>
        internal static string tagGridColumn {
            get {
                return ResourceManager.GetString("tagGridColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;/w:tblGrid&gt;.
        /// </summary>
        internal static string tagGridEnd {
            get {
                return ResourceManager.GetString("tagGridEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;w:tr wsp:rsidR=&quot;002A7E54&quot; wsp:rsidRPr=&quot;006C7DFD&quot;
        ///  wsp:rsidTr=&quot;006C7DFD&quot;&gt;.
        /// </summary>
        internal static string tagGridRow {
            get {
                return ResourceManager.GetString("tagGridRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;/w:tr&gt;.
        /// </summary>
        internal static string tagGridRowEnd {
            get {
                return ResourceManager.GetString("tagGridRowEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;w:p wsp:rsidR=&quot;006956CA&quot; wsp:rsidRDefault=&quot;00D52529&quot; wsp:rsidP=&quot;00D52529&quot;&gt;
        ///    &lt;w:pPr&gt;&lt;w:pStyle w:val=&quot;Prrafodelista&quot;/&gt;
        ///    &lt;w:listPr&gt;
        ///      &lt;w:ilvl w:val=&quot;0&quot;/&gt;
        ///      &lt;w:ilfo w:val=&quot;6&quot;/&gt;&lt;wx:t wx:val=&quot;¨&quot;/&gt;
        ///      &lt;wx:font wx:val=&quot;Wingdings&quot;/&gt;
        ///    &lt;/w:listPr&gt;
        ///      &lt;w:ind w:left=&quot;426&quot; w:hanging=&quot;284&quot;/&gt;
        ///      &lt;w:rPr&gt;&lt;w:rFonts w:cs=&quot;Calibri&quot;/&gt;
        ///        &lt;w:lang w:val=&quot;EN-US&quot;/&gt;&lt;/w:rPr&gt;&lt;/w:pPr&gt;&lt;w:r&gt;&lt;w:rPr&gt;&lt;w:rFonts w:cs=&quot;Calibri&quot;/&gt;
        ///          &lt;w:lang w:val=&quot;EN-US&quot;/&gt;
        ///        &lt;/w:rPr&gt;
        ///          &lt;w:t&gt;  &lt;/w:t&gt;
        ///        &lt; [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string tagNO {
            get {
                return ResourceManager.GetString("tagNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;w:p wsp:rsidR=&quot;006956CA&quot; wsp:rsidRDefault=&quot;006956CA&quot; wsp:rsidP=&quot;00AF04BF&quot;&gt;
        ///          &lt;w:pPr&gt;
        ///            &lt;w:pStyle w:val=&quot;Prrafodelista&quot;/&gt;
        ///            &lt;w:listPr&gt;
        ///              &lt;w:ilvl w:val=&quot;0&quot;/&gt;
        ///              &lt;w:ilfo w:val=&quot;4&quot;/&gt;
        ///              &lt;wx:t wx:val=&quot;ý&quot;/&gt;
        ///              &lt;wx:font wx:val=&quot;Wingdings&quot;/&gt;
        ///            &lt;/w:listPr&gt;
        ///            &lt;w:rPr&gt;
        ///              &lt;w:rFonts w:cs=&quot;Calibri&quot;/&gt;
        ///              &lt;w:lang w:val=&quot;EN-US&quot;/&gt;
        ///            &lt;/w:rPr&gt;
        ///          &lt;/w:pPr&gt;
        ///          &lt;w:proofErr w:type=&quot;spellStart&quot; [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string tagOK {
            get {
                return ResourceManager.GetString("tagOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;w:tblPr&gt;
        ///    &lt;w:tblW w:w=&quot;0&quot; w:type=&quot;auto&quot; /&gt;
        ///    &lt;w:tblBorders&gt;
        ///      &lt;w:top w:val=&quot;single&quot; w:sz=&quot;4&quot; wx:bdrwidth=&quot;10&quot; w:space=&quot;0&quot;
        ///      w:color=&quot;auto&quot; /&gt;
        ///      &lt;w:left w:val=&quot;single&quot; w:sz=&quot;4&quot; wx:bdrwidth=&quot;10&quot; w:space=&quot;0&quot;
        ///      w:color=&quot;auto&quot; /&gt;
        ///      &lt;w:bottom w:val=&quot;single&quot; w:sz=&quot;4&quot; wx:bdrwidth=&quot;10&quot;
        ///      w:space=&quot;0&quot; w:color=&quot;auto&quot; /&gt;
        ///      &lt;w:right w:val=&quot;single&quot; w:sz=&quot;4&quot; wx:bdrwidth=&quot;10&quot; w:space=&quot;0&quot;
        ///      w:color=&quot;auto&quot; /&gt;
        ///      &lt;w:insideH w:val=&quot;single&quot; w:sz=&quot;4&quot; wx:bdrwidth=&quot;10&quot;
        ///      w:space=&quot;0&quot; w:co [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string tagStyle {
            get {
                return ResourceManager.GetString("tagStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;w:tbl&gt;.
        /// </summary>
        internal static string tagTable {
            get {
                return ResourceManager.GetString("tagTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;/w:tbl&gt;.
        /// </summary>
        internal static string tagTableEnd {
            get {
                return ResourceManager.GetString("tagTableEnd", resourceCulture);
            }
        }
    }
}
